export const FETCHING_IMAGES_REQUEST = 'FETCHING_IMAGES_REQUEST';
export const FETCHING_IMAGES_SUCCESS = 'FETCHING_IMAGES_SUCCESS';
export const FETCHING_IMAGES_FAIL = 'FETCHING_IMAGES_FAIL';

export const FETCHING_IMAGE_REQUEST = 'FETCHING_IMAGE_REQUEST';
export const FETCHING_IMAGE_SUCCESS = 'FETCHING_IMAGE_SUCCESS';
export const FETCHING_IMAGE_FAIL = 'FETCHING_IMAGE_FAIL';
